name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: roshandhiman
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake.svg

      - name: Deploy
        run: |
          cd dist
          git init
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b output
          git add .
          git commit -m "update snake"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/roshandhiman/roshandhiman.git output
